### ISSUE TITLE
Obscure error when installing requirements [SOLVED]

### ISSUE THREAD

**Issue by scribeby** [stav121/i3wm-themer#145]
Basically I did pip install -r requirements.txt and it gave me this error (WARNING, MIGHT NOT BE SUPER ACCURATE, HAD TO USE AN AI TO TURN THE PICTURE INTO TEXT.)

exit code: 1
-> [54 lines of outputl
running egg_info
uriting 1163/PyYAML.egg-info/PKG-INFO
uriting dependency links to 11b3/PyYAML.egg-info/dependency_links.txt
writing top-level names to 1163/PyYAML.egg-info/top_level.txt
Traceback (most recent call last):
File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process_in_process.py", line 353, in <module> main()
File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks_in_process_in_process.py", line 335, in main Json_out('return_val'l hook(whook input['kwargs)
AAA
AAAAAA
File "/usr/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process_in_process.py", line 118, in get_requires_for return hook(config settings)
AAAAAAA
File "/tmp/pip-build-enu-411nrayk/over lay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_fo return self get build requires (config settings, requirements=['wheel'])
AAAAAAX AAAAAAAAAA
self.run_setup()
File "/tmp/pip-build-enu-411nrayk/overlay/lib/python3.11/site-packages/setuptools/build_neta.py", line 295, in get_build_requ File "/tmp/pip-build-enu-411nrayk/over lay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup exec(code, locals())
File "<string>", line 271, in <module>
File "/tmp/pip-build-enu-411nrayk/over lay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup return distutils.core.setup(attrs)
AAAAAAAA
File "/tmp/pip-build-enu-411nrayk/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup return run commands (dist)
AAAAAAA
dist.run_commands()
File "/tmp/pip-build-enu-411nrayk/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_comman File "/tmp/pip-build-enu-41inrayk/over lay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_comman self.run_command (cmd) File "/tmp/pip-build-enu-41inrayk/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
super().run_command(command)
cnd_obj.run()
File "/tmp/pip-build-enu-411nrayk/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_comman File /tmp/pip-build-enu-411nrayk/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 321, in run self.find sources()
File "/tmp/pip-build-enu-411nrayk/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 329, in find_sour mn.run()
File "/tmp/pip-build-enu-411nrayk/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
self.add_defaults()
File "/tmp/pip-build-enu-411nrayk/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defau
sdist.add_defaults(self)
File "/tmp/pip-build-enu-411nrayk/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 112, in add_defaults super().add defaults()
File "/tmp/pip-build-enu-41inrayk/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in a
self._add_defaults_ext()
File "/tmp/pip-build-enu-411nrayk/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _
self.filelist.extend(build_ext.get_source_files())
File "<string>", line 201, in get_source_files
File "/tmp/pip-build-enu-411nrayk/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in ___getattr_ raise AttributeError(attr) AttributeError: cython_sources
[end of output)
note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
* Getting requirements to build wheel did not run successfully.
exit code: 1
-> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip. [root@archlinux 13um-themer 18

What do I do?

**Comment by stav121** [comment]
Hello sir,

I cannot determine what is going on here without any additional information. Could you please provide some more info:

* Your OS and version
* Your python version (python3 --version)
* Your pip version etc

Also the logs are kinda hard to reed that way, I would appreciate maybe a screenshot or something.

**Comment by scribeby** [comment]
Solved it, sorry forgot to mark it as solved.

**Comment by pr0fsmith** [comment]
How did you solve it? I'm getting the same error.  Using NixOS and Python 311
